/sensing/lidar/no_ground/pointcloud:
  depth: 10
  durability: volatile
  history: keep_last
  reliability: best_effort
/sensing/lidar/top/velodyne_packets:
  depth: 10
  durability: volatile
  history: keep_last
  reliability: best_effort
/perception/obstacle_segmentation/pointcloud:
  depth: 10
  durability: volatile
  history: keep_last
  reliability: best_effort
/diagnostics:
  durability: volatile
  history: keep_all
  reliability: best_effort
