site_name: Autoware Documentation
site_url: https://tier4.github.io/autoware.proj
repo_url: https://github.com/tier4/autoware.proj
edit_uri: edit/main/docs
docs_dir: docs
theme:
  name: material
  feature:
    tabs: true
  favicon: images/tier4.png
  icon:
    repo: fontawesome/brands/github
extra:
  font:
    text: "Noto Sans JP"
    code: "Consolas"
plugins:
  - same-dir
  - search
copyright: "Copyright &copy; 2021 Tier IV, Inc."

markdown_extensions:
  - codehilite: { guess_lang: false }
  - fontawesome_markdown
  - mdx_math
  - mdx_truly_sane_lists: { nested_indent: 2 }
  - mdx_unimoji
  - plantuml_markdown: { server: "http://www.plantuml.com/plantuml" }
  - pymdownx.arithmatex
  - pymdownx.highlight
  - pymdownx.superfences
  - toc: { permalink: "#" }

extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
  - css/tier4_color.css
extra_javascript:
  - "https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML"

nav:
  - Home: .
  - Tutorials:
      - Requirements: tutorial/Requirements.md
      - How to install: tutorial/HowToInstall.md
      - How to run:
          - Quick start: tutorial/QuickStart.md
          - Simulation: tutorial/SimulationTutorial.md
  - Design:
      - API:
          - Concept: design/apis/ja/concept.md
          - List: design/apis/ja/list.md
          - Proposal:
              - State: design/apis/ja/state.md
      - Architecture:
          - Overview: design/software_architecture/Overview.md
          - Sensing: design/software_architecture/Sensing/Sensing.md
          - Localization:
              - Overall: design/software_architecture/Localization/Localization.md
              - Pose estimator: design/software_architecture/Localization/PoseEstimator/PoseEstimator.md
              - Twist estimator: design/software_architecture/Localization/TwistEstimator/TwistEstimator.md
              - Pose twist fusion filter: design/software_architecture/Localization/PoseTwistFusionFilter/PoseTwistFusionFilter.md
          - Perception:
              - Overall: design/software_architecture/Perception/Perception.md
              - Object recognition:
                  - Detection: design/software_architecture/Perception/ObjectRecognition/Detection/Detection.md
                  - Tracking: design/software_architecture/Perception/ObjectRecognition/Tracking/Tracking.md
                  - Prediction: design/software_architecture/Perception/ObjectRecognition/Prediction/Prediction.md
              - Traffic light recognition:
                  - Detection: design/software_architecture/Perception/TrafficLightRecognition/Detection/Detection.md
                  - Classification: design/software_architecture/Perception/TrafficLightRecognition/Classification/Classification.md
          - Planning:
              - Overall: design/software_architecture/Planning/Planning.md
              - Scenario selector: design/software_architecture/Planning/ScenarioSelector/ScenarioSelector.md
              - Lane driving Scenario:
                  - Overall: design/software_architecture/Planning/LaneDriving/LaneDrivingScenario.md
                  - Behavior path planning: design/software_architecture/Planning/LaneDriving/Behavior/LaneChangePlanner.md
                  - Behavior velocity planning: design/software_architecture/Planning/LaneDriving/Behavior/BehaviorVelocityPlanner.md
              - Parking: design/software_architecture/Planning/Parking/ParkingScenario.md
              - Design rationale: design/software_architecture/Planning/DesignRationale.md
          - Control:
              - Overall: design/software_architecture/Control/Control.md
              - Trajectory follower:
                  - Lateral controller: design/software_architecture/Control/TrajectoryFollower/LateralController.md
                  - Longitudinal controller: design/software_architecture/Control/TrajectoryFollower/LongitudinalController.md
                  - Lateral longitudinal coupler: design/software_architecture/Control/TrajectoryFollower/LatLonCoupler.md
              - Vehicle cmd gate: design/software_architecture/Control/VehicleCmdGate/VehicleCmdGate.md
          - Vehicle: design/software_architecture/Vehicle/Vehicle.md
          - Map: design/software_architecture/Map/Map.md
          - TF: design/software_architecture/TF.md
          - Naming convention: design/software_architecture/NamingConvention.md
          - For developers: design/software_architecture/ForDevelopers.md
          - Node diagram: design/software_architecture/NodeDiagram.md
      - Repository: design/repository/Repository.md
      - Release: design/release/Release.md
  - UserGuide:
      - RViz panels: user_guide/RVizPanels.md
  - DeveloperGuide:
      - Coding guideline: developer_guide/CodingGuideline.md
      - Pull request guideline: developer_guide/PullRequestGuideline.md
      - Unit test guideline: developer_guide/UnitTestGuideline.md
      - Clang-Tidy guideline: developer_guide/ClangTidyGuideline.md
      - Knowhow:
          - developer_guide/knowhow/PortingToROS2.md
  - License/Credit:
      - Credits: Credits.md
      - License: License.md
