---
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes
  become: yes

- name: Add autonomoustuff-public.list
  file:
    path: /etc/apt/sources.list.d/autonomoustuff-public.list
    owner: root
    group: root
    mode: 0644
    state: touch
  become: yes

- name: Get lsb release
  shell: lsb_release -sc
  register: lsb_release

- name: Add autonomoustuff public repo
  lineinfile:
    path: /etc/apt/sources.list.d/autonomoustuff-public.list
    line: "deb [trusted=yes] https://s3.amazonaws.com/autonomoustuff-repo/ {{ lsb_release.stdout }} main"
    state: present
  become: yes

- name: Add rosdep list file for autonomoustuff
  file:
    path: /etc/ros/rosdep/sources.list.d/40-autonomoustuff-public-{{ rosdistro }}.list
    owner: root
    group: root
    mode: 0644
    state: touch
  become: yes

- name: Add autonomoustuff rosdep yaml
  lineinfile:
    path: /etc/ros/rosdep/sources.list.d/40-autonomoustuff-public-{{ rosdistro }}.list
    line: "yaml https://s3.amazonaws.com/autonomoustuff-repo/autonomoustuff-public-{{ rosdistro }}.yaml"
    state: present
  become: yes
