name: vcs-import

on:
  pull_request:
    paths:
      - autoware.proj.repos
  workflow_dispatch:

jobs:
  vcs-import:
    runs-on: ubuntu-latest
    container: ros:galactic
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install pip for rosdep
        run: |
          sudo apt-get -y update
          sudo apt-get -y install python3-pip

      - name: Register AutonomouStuff repository
        uses: autowarefoundation/autoware-github-actions/register-autonomoustuff-repository@v1
        with:
          rosdistro: galactic

      - name: Register kvaser repository
        run: |
          sudo apt-get -y install software-properties-common
          sudo apt-add-repository ppa:astuff/kvaser-linux

      - name: Set git config for private repositories
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global url.https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/.insteadOf 'https://github.com/'
          git config --global url.https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/.insteadOf 'git@github.com:'

      - name: Run vcs import
        run: |
          mkdir src
          vcs import src < autoware.proj.repos

      - name: Run rosdep install
        run: |
          sudo apt-get -y update
          rosdep update
          DEBIAN_FRONTEND=noninteractive rosdep install -y --from-paths src --ignore-src --rosdistro galactic
